### PR TITLE
Make equation and optimization evaluate modules public

### LINKED ISSUE #235: Make equation evaluate module public in twine-solvers
## Problem

The `evaluate` module in `twine-solvers::equation` is currently `pub(crate)`, which prevents downstream code from properly handling errors during solver iteration.

In twine-models (#21), we're using `bisection::solve` with an observer to recover from second law violations during iteration. The legacy code pattern-matched on the specific error:

```rust
|event: &bisection::Event<'_, _, _>| {
    if let Err(EvalError::Model(SolveError::SecondLawViolation { .. })) = event.result() {
        return Some(bisection::Action::assume_positive());
    }
    None
}
```

But since `EvalError` is private, we're forced to catch all errors:

```rust
if event.result().is_err() {
    return Some(bisection::Action::assume_positive());
}
```

This hides errors that users should see (e.g., thermo model failures).

## Proposal

Make the evaluate module public:

- `evaluate()` - maps x → input → model call → residuals
- `Evaluation` - result struct with x, residuals, and snapshot
- `EvalError` - distinguishes model errors from problem errors

## Rationale

twine-core exports `EquationProblem`, `OptimizationProblem`, etc. as public traits, signaling that third parties can write their own solvers. Those solvers would benefit from the same evaluation infrastructure:

1. `evaluate()` is solver-agnostic—useful for any solver, not just bisection
2. `EvalError` lets observers/callbacks distinguish error sources
3. `Evaluation` provides a standard result format

These are generic building blocks, not implementation details of specific solvers.

### PR DESCRIPTION
**Pull request by dyreby**
Closes #235

Exports `EvalError`, `EvaluateResult`, `Evaluation`, and `evaluate()` from both `equation` and `optimization` modules.

## Motivation

Since twine-core exports `EquationProblem`, `OptimizationProblem`, etc. as public traits, third parties can write their own solvers. Those solvers benefit from the same evaluation infrastructure:

- `evaluate()` — maps x → input → model call → residuals/objective
- `Evaluation` — result struct with x, residuals/objective, and snapshot
- `EvalError` — distinguishes model errors from problem errors

## Use Case

In twine-models, we use `bisection::solve` with an observer to recover from second law violations during iteration. With `EvalError` public, we can match specifically:

```rust
|event: &bisection::Event<'_, _, _>| {
    if let Err(EvalError::Model(SolveError::SecondLawViolation { .. })) = event.result() {
        return Some(bisection::Action::assume_positive());
    }
    None
}
```

Without it, we're forced to catch all errors, hiding issues users should see.

### CODE REVIEW

File: crates/solvers/src/equation.rs [hunk 1]
```diff
@@ -1,4 +1,5 @@
-pub(crate) mod evaluate;
-pub(crate) use evaluate::{EvalError, EvaluateResult, Evaluation, evaluate};
+mod evaluate;
+
+pub use evaluate::{EvalError, EvaluateResult, Evaluation, evaluate};
```
Comment (dyreby) [inline crates/solvers/src/equation.rs]: Was it intentional to promote evaluate stuff to `equation::Evaluation`, vs `equation::evaluate::Evaluation`? I'm ok if you have a good reason. Justify this API.

**Review by gdtroszak — APPROVED** [review]
Straightforward visibility change. Looks good.
